"""add tool table

Revision ID: ac75185aa6b3
Revises: d3c351eeefb7
Create Date: 2022-11-23 03:45:32.486138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac75185aa6b3'
down_revision = 'd3c351eeefb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('question1', sa.Boolean(), nullable=True),
    sa.Column('question2', sa.Boolean(), nullable=True),
    sa.Column('question3', sa.Boolean(), nullable=True),
    sa.Column('question4', sa.Boolean(), nullable=True),
    sa.Column('question5', sa.Boolean(), nullable=True),
    sa.Column('question6', sa.Boolean(), nullable=True),
    sa.Column('question7', sa.Boolean(), nullable=True),
    sa.Column('question8', sa.Boolean(), nullable=True),
    sa.Column('question9', sa.Boolean(), nullable=True),
    sa.Column('question10', sa.Boolean(), nullable=True),
    sa.Column('question11', sa.Boolean(), nullable=True),
    sa.Column('question12', sa.Boolean(), nullable=True),
    sa.Column('question13', sa.Boolean(), nullable=True),
    sa.Column('question14', sa.Boolean(), nullable=True),
    sa.Column('question15', sa.Boolean(), nullable=True),
    sa.Column('question16', sa.Boolean(), nullable=True),
    sa.Column('question17', sa.Boolean(), nullable=True),
    sa.Column('question18', sa.Boolean(), nullable=True),
    sa.Column('question19', sa.Boolean(), nullable=True),
    sa.Column('question20', sa.Boolean(), nullable=True),
    sa.Column('question21', sa.Boolean(), nullable=True),
    sa.Column('question22', sa.Boolean(), nullable=True),
    sa.Column('question23', sa.Boolean(), nullable=True),
    sa.Column('question24', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool')
    # ### end Alembic commands ###
